export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const ACTIVE_LOADING = 'ACTIVE_LOADING';
export const ACTIVE_SUCCESS = 'ACTIVEP_SUCCESS';
export const ACTIVE_FAIL = 'ACTIVE_FAIL';
